<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // OLI
            [
                'kode_item' => 'OLI-MPX1-08',
                'nama_item' => 'Oli MPX 1 0.8L (Bebek)',
                'jenis' => 'Oli',
                'merk' => 'AHM Oil',
                'satuan' => 'Botol',
                'harga_pokok' => 45000,
                'up_persen' => 22.22,
                'harga_jual' => 55000,
                'stok' => 50,
                'stok_minimum' => 10,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'OLI-MPX2-08',
                'nama_item' => 'Oli MPX 2 0.8L (Matic)',
                'jenis' => 'Oli',
                'merk' => 'AHM Oil',
                'satuan' => 'Botol',
                'harga_pokok' => 47000,
                'up_persen' => 17.02,
                'harga_jual' => 55000,
                'stok' => 60,
                'stok_minimum' => 10,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'OLI-YAMALUBE-MATIC',
                'nama_item' => 'Oli Yamalube Matic 0.8L',
                'jenis' => 'Oli',
                'merk' => 'Yamalube',
                'satuan' => 'Botol',
                'harga_pokok' => 42000,
                'up_persen' => 19.05,
                'harga_jual' => 50000,
                'stok' => 45,
                'stok_minimum' => 10,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'OLI-SHELL-AX7',
                'nama_item' => 'Oli Shell Advance AX7 Scooter',
                'jenis' => 'Oli',
                'merk' => 'Shell',
                'satuan' => 'Botol',
                'harga_pokok' => 55000,
                'up_persen' => 18.18,
                'harga_jual' => 65000,
                'stok' => 30,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],

            // BAN
            [
                'kode_item' => 'BAN-IRC-7090-17',
                'nama_item' => 'Ban Luar IRC 70/90-17 (NR73)',
                'jenis' => 'Ban',
                'merk' => 'IRC',
                'satuan' => 'Pcs',
                'harga_pokok' => 180000,
                'up_persen' => 16.67,
                'harga_jual' => 210000,
                'stok' => 20,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'BAN-IRC-8090-17',
                'nama_item' => 'Ban Luar IRC 80/90-17 (NR73)',
                'jenis' => 'Ban',
                'merk' => 'IRC',
                'satuan' => 'Pcs',
                'harga_pokok' => 210000,
                'up_persen' => 14.29,
                'harga_jual' => 240000,
                'stok' => 15,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'BAN-FDR-8090-14',
                'nama_item' => 'Ban Luar FDR 80/90-14 Tubeless',
                'jenis' => 'Ban',
                'merk' => 'FDR',
                'satuan' => 'Pcs',
                'harga_pokok' => 220000,
                'up_persen' => 18.18,
                'harga_jual' => 260000,
                'stok' => 25,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'BAN-FDR-9090-14',
                'nama_item' => 'Ban Luar FDR 90/90-14 Tubeless',
                'jenis' => 'Ban',
                'merk' => 'FDR',
                'satuan' => 'Pcs',
                'harga_pokok' => 260000,
                'up_persen' => 15.38,
                'harga_jual' => 300000,
                'stok' => 20,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],

            // SPAREPART MESIN & KELISTRIKAN
            [
                'kode_item' => 'BUSI-NGK-C7HSA',
                'nama_item' => 'Busi NGK C7HSA (Grand/Supra)',
                'jenis' => 'Kelistrikan',
                'merk' => 'NGK',
                'satuan' => 'Pcs',
                'harga_pokok' => 12000,
                'up_persen' => 25,
                'harga_jual' => 15000,
                'stok' => 100,
                'stok_minimum' => 20,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'BUSI-NGK-CPR9',
                'nama_item' => 'Busi NGK CPR9EA-9 (Vario 125/150)',
                'jenis' => 'Kelistrikan',
                'merk' => 'NGK',
                'satuan' => 'Pcs',
                'harga_pokok' => 15000,
                'up_persen' => 33.33,
                'harga_jual' => 20000,
                'stok' => 80,
                'stok_minimum' => 15,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'AKI-GS-GTZ5S',
                'nama_item' => 'Aki GS Astra GTZ5S (MF)',
                'jenis' => 'Kelistrikan',
                'merk' => 'GS Astra',
                'satuan' => 'Pcs',
                'harga_pokok' => 230000,
                'up_persen' => 19.57,
                'harga_jual' => 275000,
                'stok' => 10,
                'stok_minimum' => 3,
                'pajak_include' => true,
            ],
            
            // PENGEREMAN
            [
                'kode_item' => 'KAMPAS-REM-DPN-BEAT',
                'nama_item' => 'Kampas Rem Depan Beat/Vario (Dispad)',
                'jenis' => 'Pengereman',
                'merk' => 'AHM',
                'satuan' => 'Set',
                'harga_pokok' => 45000,
                'up_persen' => 33.33,
                'harga_jual' => 60000,
                'stok' => 30,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'KAMPAS-REM-BLK-BEAT',
                'nama_item' => 'Kampas Rem Belakang Beat/Vario',
                'jenis' => 'Pengereman',
                'merk' => 'AHM',
                'satuan' => 'Set',
                'harga_pokok' => 35000,
                'up_persen' => 28.57,
                'harga_jual' => 45000,
                'stok' => 30,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],

            // GEAR & RANTAI
            [
                'kode_item' => 'RANTAI-KIT-SUPRA125',
                'nama_item' => 'Gear Set Supra X 125',
                'jenis' => 'Gear Set',
                'merk' => 'Indoparts',
                'satuan' => 'Set',
                'harga_pokok' => 140000,
                'up_persen' => 25,
                'harga_jual' => 175000,
                'stok' => 12,
                'stok_minimum' => 3,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'RANTAI-KIT-VIXION',
                'nama_item' => 'Gear Set Vixion New',
                'jenis' => 'Gear Set',
                'merk' => 'Yamaha Genuine',
                'satuan' => 'Set',
                'harga_pokok' => 280000,
                'up_persen' => 17.86,
                'harga_jual' => 330000,
                'stok' => 8,
                'stok_minimum' => 2,
                'pajak_include' => true,
            ],

            // CVT
            [
                'kode_item' => 'ROLLER-VARIO-125',
                'nama_item' => 'Roller Vario 125 (Set)',
                'jenis' => 'CVT',
                'merk' => 'AHM',
                'satuan' => 'Set',
                'harga_pokok' => 55000,
                'up_persen' => 27.27,
                'harga_jual' => 70000,
                'stok' => 25,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'V-BELT-BEAT-FI',
                'nama_item' => 'V-Belt Beat FI',
                'jenis' => 'CVT',
                'merk' => 'AHM',
                'satuan' => 'Pcs',
                'harga_pokok' => 85000,
                'up_persen' => 29.41,
                'harga_jual' => 110000,
                'stok' => 20,
                'stok_minimum' => 5,
                'pajak_include' => true,
            ],
            [
                'kode_item' => 'V-BELT-NMAX',
                'nama_item' => 'V-Belt NMAX',
                'jenis' => 'CVT',
                'merk' => 'Yamaha Genuine',
                'satuan' => 'Pcs',
                'harga_pokok' => 120000,
                'up_persen' => 25,
                'harga_jual' => 150000,
                'stok' => 15,
                'stok_minimum' => 3,
                'pajak_include' => true,
            ],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['kode_item' => $item['kode_item']], // Kunci pencarian agar tidak duplikat
                $item
            );
        }
    }
}
